{% set name = "hubstore" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hubstore-{{ version }}.tar.gz
  sha256: e3bbc9a59df6ab83a18b2dc284ae938db4b7e9e3c885b49480b40c06ea6ea8ec

build:
  entry_points:
    - hubstore = hubstore.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - tkf

test:
  imports:
    - hubstore
  commands:
    - pip check
    # CLI not quite implemented yet upstream
    # - hubstore --help
  requires:
    - pip

about:
  home: https://github.com/pyrustic/hubstore
  summary: Distribute, promote, discover, install, and run Python desktop applications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
